### ISSUE TITLE
Registering custom UUID deserializer fails.

### ISSUE THREAD

**Issue by ahmetkucuk** [ramonhagenaars/jsons#52]
Trying to do:
```
import uuid
import jsons

def custom_uuid_serializer(obj: uuid.UUID, **kwargs) -> str:
	return str(obj)

def custom_uuid_deserializer(obj: str, cls, **kwargs) -> uuid.UUID:
	return uuid.UUID(obj)
	
jsons.set_serializer(custom_uuid_serializer, uuid.UUID) # Failed...
jsons.set_deserializer(custom_uuid_deserializer, uuid.UUID) # Failed...
```

Exception:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "json_test.py", line 36, in <module>
    data = jsons.dump(hearthbeat) # It will serialize uuid to its bytes
  File "/Users/ahmetkucuk/anaconda3/envs/jsons/lib/python3.7/site-packages/jsons/_dump_impl.py", line 52, in dump
    raise SerializationError(str(err))
jsons.exceptions.SerializationError: 'uuid.UUID'
```

I think the issue is here: https://github.com/ramonhagenaars/jsons/blob/master/jsons/_lizers_impl.py#L139

`        result = lizers[pname.lower()]` solves the issue.

**Comment by ramonhagenaars** [comment]
Thanks ahmetkucuk, for your issue and your PR!

It took me a minute to reproduce your problem and I found that the problem occurs when I do this in addition to your code:

```python
dumped = jsons.dump(uuid.UUID('a8098c1a-f86e-11da-bd1a-00112444be1e'))
jsons.load(dumped, uuid.UUID)  # This is where I get the error.
```

Your suggestion seem legit, I'll look into your PR.

**Comment by ramonhagenaars** [comment]
Thanks ahmetkucuk. This issue has been deployed in version [0.8.8](https://pypi.org/project/jsons/).

**Comment by ahmetkucuk** [comment]
Thank you!
