### ISSUE TITLE
Serialization of unspecified length of Tuple fails

### ISSUE THREAD

**Issue by ahmetkucuk** [ramonhagenaars/jsons#85]
The following serialization fails when I use `strict=True`, I am not sure whether this is expected behavior or not.

```
>>> from typing import Tuple
>>> from dataclasses import dataclass
>>> import jsons
>>> @dataclass(frozen=True)
... class A:
...     x: Tuple[str, ...]
... 
>>> jsons.dumps(A('abc'), strict=True)
```

Error:
```
Traceback (most recent call last):
  File "~/.pyenv/versions/forms/lib/python3.7/site-packages/jsons/_dump_impl.py", line 62, in _do_dump
    result = serializer(obj, cls=cls, **kwargs)
  File "~/.pyenv/versions/forms/lib/python3.7/site-packages/jsons/serializers/default_object.py", line 92, in default_object_serializer
    fork_inst=fork_inst)
  File "~/.pyenv/versions/forms/lib/python3.7/site-packages/jsons/serializers/default_object.py", line 126, in _do_serialize
    **kwargs)
  File "~/.pyenv/versions/forms/lib/python3.7/site-packages/jsons/_dump_impl.py", line 57, in dump
    return _do_dump(obj, serializer, cls, initial, kwargs_)
  File "~/.pyenv/versions/forms/lib/python3.7/site-packages/jsons/_dump_impl.py", line 68, in _do_dump
    raise SerializationError(str(err))
jsons.exceptions.SerializationError: Not enough generic types (2) in typing.Tuple[str, ...], expected 3 to match the iterable of length 3
```

**Comment by ramonhagenaars** [comment]
In your code, you're providing a string as an argument for `x` to `A` rather than a tuple of strings. However, that seems to fail still.

It should be fixed in this pull request: https://github.com/ramonhagenaars/jsons/pull/86

**Comment by ahmetkucuk** [comment]
Right, I was just trying to reproduce with a small example.
